http:
  routers:
    backend-personnel:
      entryPoints:
        - web
      rule: PathPrefix(`/api/personnel`)
      middlewares:
        # middlewares are defined in backend.yaml
        - api-strip-prefix
        - api-headers
      service: backend-personnel
  services:
    backend-personnel:
      loadBalancer:
        servers:
          - url: http://backend-personnel:9000
          #- url: http://host.docker.internal:9000